### PR TITLE
Fallback to the shadows value of the IconTheme

### PR DESCRIPTION
**Pull request by remi-denele**
With the current implementation, some properties of the icon can be inherited from the `IconTheme` like the icon size, its color etc. but it is not the case for the `shadows` property.

This PR adds a fallback to `iconTheme.shadows` if `icon.shadow` is not defined.

Merci :)

### CODE REVIEW

**Review by TesteurManiak — APPROVED** [review]

**Comment by remi-denele** [comment]
Done!

**Comment by remi-denele** [comment]
Any chance to publish a new version with the fix to pub.dev?

**Comment by TesteurManiak** [comment]
@remi-denele I have to fix some issues with the dependency used to generate the golden tests beforehand.
Note that you can make the dependency point to a git repository if you don't want to wait for a release on pub.
```yaml
dependencies:
  icon_decoration:
    git:
      url: https://github.com/TesteurManiak/icon_decoration.git
      ref: main
```

**Comment by remi-denele** [comment]
We are still pointing to our fork for now with a `dependency_overrides` so no problem.
It was just to know if there was a blocking point, so thanks for the answer.

**Comment by TesteurManiak** [comment]
@remi-denele v2.1.0 is published https://pub.dev/packages/icon_decoration/versions/2.1.0

**Pull request merged**
